version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:23.0.7
    hostname: keycloak_test
    ports:
      - "8543:8080"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=password"
      - "JAVA_OPTS=-Djboss.http.port=8080"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=host.docker.internal"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_PASSWORD=keycloak"
    depends_on:
      - postgres
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
volumes:
      postgres_data: